"""Remove Unique for upload audit sha256

Revision ID: 224e4fea3514
Revises: d30ae8daa166
Create Date: 2026-04-27 04:42:47.271466
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '224e4fea3514'
down_revision: Union[str, None] = 'd30ae8daa166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_audit_file_sha256'), table_name='upload_audit')
    op.create_index('ix_upload_audit_file_sha256', 'upload_audit', ['file_sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_upload_audit_file_sha256', table_name='upload_audit')
    # ### end Alembic commands ###
