"""initial_start_schema

Revision ID: 40dcff5d5206
Revises: 
Create Date: 2026-04-25 22:18:22.403543
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '40dcff5d5206'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_company',
    sa.Column('company_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entity_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_index(op.f('ix_dim_company_entity_name'), 'dim_company', ['entity_name'], unique=True)
    op.create_table('dim_country',
    sa.Column('country_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('country_name', sa.Text(), nullable=False),
    sa.Column('iso_alpha2', sa.Text(), nullable=True),
    sa.Column('iso_alpha3', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('country_id'),
    sa.UniqueConstraint('country_name')
    )
    op.create_index('ix_dim_country_name', 'dim_country', ['country_name'], unique=False)
    op.create_table('dim_currency',
    sa.Column('currency_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('currency_code', sa.Text(), nullable=False),
    sa.Column('currency_name', sa.Text(), nullable=True),
    sa.Column('symbol', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('currency_id')
    )
    op.create_index('ix_dim_currency_code', 'dim_currency', ['currency_code'], unique=False)
    op.create_index(op.f('ix_dim_currency_currency_code'), 'dim_currency', ['currency_code'], unique=True)
    op.create_table('dim_date',
    sa.Column('date_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('year_value', sa.Text(), nullable=False),
    sa.Column('calendar_year', sa.Integer(), nullable=True),
    sa.Column('is_estimate', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date_id')
    )
    op.create_index('ix_dim_date_sort_order', 'dim_date', ['sort_order'], unique=False)
    op.create_index(op.f('ix_dim_date_year_value'), 'dim_date', ['year_value'], unique=True)
    op.create_table('upload_audit',
    sa.Column('upload_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('file_sha256', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('rows_extracted', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed')", name='ck_upload_audit_status'),
    sa.PrimaryKeyConstraint('upload_id')
    )
    op.create_index('ix_upload_audit_file_sha256', 'upload_audit', ['file_sha256'], unique=True)
    op.create_index('ix_upload_audit_status', 'upload_audit', ['status'], unique=False)
    op.create_index('ix_upload_audit_uploaded_at', 'upload_audit', ['uploaded_at'], unique=False)
    op.create_table('company_versions',
    sa.Column('version_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['dim_company.company_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_audit.upload_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index('ix_company_versions_company_id', 'company_versions', ['company_id'], unique=False)
    op.create_index('ix_company_versions_is_current', 'company_versions', ['company_id', 'is_current'], unique=False)
    op.create_index('ix_company_versions_temporal', 'company_versions', ['company_id', 'valid_from', 'valid_to'], unique=False)
    op.create_table('snapshot_fact',
    sa.Column('snapshot_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('country_id', sa.Uuid(), nullable=True),
    sa.Column('currency_id', sa.Uuid(), nullable=True),
    sa.Column('entity_name', sa.Text(), nullable=False),
    sa.Column('corporate_sector', sa.Text(), nullable=True),
    sa.Column('country_name', sa.Text(), nullable=True),
    sa.Column('currency_code', sa.Text(), nullable=True),
    sa.Column('accounting_principles', sa.Text(), nullable=True),
    sa.Column('business_year_end', sa.Text(), nullable=True),
    sa.Column('rating_methodologies', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('industry_risk_name', sa.Text(), nullable=True),
    sa.Column('industry_risk_score', sa.Text(), nullable=True),
    sa.Column('industry_weight', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('segmentation_criteria', sa.Text(), nullable=True),
    sa.Column('business_risk_profile', sa.Text(), nullable=True),
    sa.Column('financial_risk_profile', sa.Text(), nullable=True),
    sa.Column('risk_sub_scores', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('credit_metrics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['dim_company.company_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['country_id'], ['dim_country.country_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['currency_id'], ['dim_currency.currency_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_audit.upload_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['version_id'], ['company_versions.version_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_index('ix_snapshot_at', 'snapshot_fact', ['snapshot_at'], unique=False)
    op.create_index('ix_snapshot_company_id', 'snapshot_fact', ['company_id'], unique=False)
    op.create_index('ix_snapshot_company_time', 'snapshot_fact', ['company_id', 'snapshot_at'], unique=False)
    op.create_index('ix_snapshot_country', 'snapshot_fact', ['country_name'], unique=False)
    op.create_index('ix_snapshot_currency', 'snapshot_fact', ['currency_code'], unique=False)
    op.create_index(op.f('ix_snapshot_fact_company_id'), 'snapshot_fact', ['company_id'], unique=False)
    op.create_index(op.f('ix_snapshot_fact_upload_id'), 'snapshot_fact', ['upload_id'], unique=False)
    op.create_index(op.f('ix_snapshot_fact_version_id'), 'snapshot_fact', ['version_id'], unique=False)
    op.create_index('ix_snapshot_sector', 'snapshot_fact', ['corporate_sector'], unique=False)
    op.create_table('data_quality_report',
    sa.Column('report_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('completeness_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('validity_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('total_fields', sa.Integer(), nullable=False),
    sa.Column('present_fields', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshot_fact.snapshot_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_audit.upload_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_data_quality_report_upload_id'), 'data_quality_report', ['upload_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_quality_report_upload_id'), table_name='data_quality_report')
    op.drop_table('data_quality_report')
    op.drop_index('ix_snapshot_sector', table_name='snapshot_fact')
    op.drop_index(op.f('ix_snapshot_fact_version_id'), table_name='snapshot_fact')
    op.drop_index(op.f('ix_snapshot_fact_upload_id'), table_name='snapshot_fact')
    op.drop_index(op.f('ix_snapshot_fact_company_id'), table_name='snapshot_fact')
    op.drop_index('ix_snapshot_currency', table_name='snapshot_fact')
    op.drop_index('ix_snapshot_country', table_name='snapshot_fact')
    op.drop_index('ix_snapshot_company_time', table_name='snapshot_fact')
    op.drop_index('ix_snapshot_company_id', table_name='snapshot_fact')
    op.drop_index('ix_snapshot_at', table_name='snapshot_fact')
    op.drop_table('snapshot_fact')
    op.drop_index('ix_company_versions_temporal', table_name='company_versions')
    op.drop_index('ix_company_versions_is_current', table_name='company_versions')
    op.drop_index('ix_company_versions_company_id', table_name='company_versions')
    op.drop_table('company_versions')
    op.drop_index('ix_upload_audit_uploaded_at', table_name='upload_audit')
    op.drop_index('ix_upload_audit_status', table_name='upload_audit')
    op.drop_index('ix_upload_audit_file_sha256', table_name='upload_audit')
    op.drop_table('upload_audit')
    op.drop_index(op.f('ix_dim_date_year_value'), table_name='dim_date')
    op.drop_index('ix_dim_date_sort_order', table_name='dim_date')
    op.drop_table('dim_date')
    op.drop_index(op.f('ix_dim_currency_currency_code'), table_name='dim_currency')
    op.drop_index('ix_dim_currency_code', table_name='dim_currency')
    op.drop_table('dim_currency')
    op.drop_index('ix_dim_country_name', table_name='dim_country')
    op.drop_table('dim_country')
    op.drop_index(op.f('ix_dim_company_entity_name'), table_name='dim_company')
    op.drop_table('dim_company')
    # ### end Alembic commands ###
