"""added_current_snapshot_foreign_key_company

Revision ID: d30ae8daa166
Revises: 40dcff5d5206
Create Date: 2026-04-26 11:42:55.237653
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'd30ae8daa166'
down_revision: Union[str, None] = '40dcff5d5206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_company', sa.Column('current_snapshot_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_dim_company_current_snapshot_id'), 'dim_company', ['current_snapshot_id'], unique=False)
    op.create_foreign_key(None, 'dim_company', 'snapshot_fact', ['current_snapshot_id'], ['snapshot_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dim_company', type_='foreignkey')
    op.drop_index(op.f('ix_dim_company_current_snapshot_id'), table_name='dim_company')
    op.drop_column('dim_company', 'current_snapshot_id')
    # ### end Alembic commands ###
